spring:
    application:
        name: JewelryProduction
    datasource:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://localhost:1433;database=Jewelry_Production_Order;encrypt=true;trustServerCertificate=true
        username: sa
        password: 1234
    jpa:
        hibernate:
            ddl-auto: update
***REMOVED***
            hibernate:
                dialect: org.hibernate.dialect.SQLServerDialect
                jdbc:
                    time_zone: Asia/Ho_Chi_Minh
        show-sql: true

***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***

***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***