spring:
    application:
        name: JewelryProduction
    datasource:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://localhost:1433;database=Jewelry_Production_Order;encrypt=true;trustServerCertificate=true
        username: sa
        password: 1234
    jpa:
        hibernate:
            ddl-auto: create-drop
***REMOVED***
            hibernate:
                dialect: org.hibernate.dialect.SQLServerDialect
                jdbc:
                    time_zone: Asia/Ho_Chi_Minh
        show-sql: true

    security:
        oauth2:
          client:
              registration:
                github:
                    client-id: Iv23licuS2tt7ELgah2s
                    client-secret: 2eb334d75f6781a5a96619eb92081500d0e974ed