#website url to crawl
page:
    url: ${URL:https://www.goldrate24.com/gold-prices/}

firebase:
    url: ${CONFIG_PATH}

spring:
    application:
        name: JewelryProduction
    datasource:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.SQLServerDialect
                jdbc:
                    time_zone: Asia/Ho_Chi_Minh
        show-sql: true
